### ISSUE TITLE
Show sensor values in the device icon

### ISSUE THREAD

**Issue by barts2108** [tim-hellhake/luftdaten-adapter#3]
Right now the luftdaten sensor is a Custom Thing, while it consists of one ore more sensors "aus der reihe" PN2.5, PN10, Temperature and Humidity. 

Would it be possible to make it so that the thing shows one of those values on the main screen ?

(kind of feature request)

**Comment by tim-hellhake** [comment]
> Would it be possible to make it so that the thing shows one of those values on the main screen?

It depends.
A device can advertise multiple [capabilities](https://iot.mozilla.org/schemas/).
You can select which property you want to see by selecting the corresponding capability in the device view.
There is a capability for the `TemperatureSensor` and a generic `MultiLevelSensor` capability for other values.
I can only advertise one property for the `MultiLevelSensor`.
If there are two values like PN2.5 and PN10 I would have to decide which one to use.
Also, I need a min and a max value for the `MultiLevelSensor`.

I'll add the capability for the `TemperatureSensor` later but I'm not sure how to proceed with the other values.

**Comment by barts2108** [comment]
(quite new to all this) I assume with "device view" you mean the page after pressing + on the Things page ? Then I have no possibility to select anything but `custom view` 

I had some look around and see in a weather add-on what you mean with the `TemperatureSensor` and `MultiLevelSensor`. I guess this is currently a limitation of the core.

**Comment by tim-hellhake** [comment]
> I assume with "device view" you mean the page after pressing + on the Things page ? 

You can see it in multiple views.
When you first add the devices you can select which capability should be the primary one.

![image](https://user-images.githubusercontent.com/17127122/79487045-eb63a280-8017-11ea-9fad-cceab12b56eb.png)

You can also change it afterward if you click on edit.

The gateway renders the devices according to their primary capability.
On the left, you can see what the `TemperatureSensor` looks like.

![image](https://user-images.githubusercontent.com/17127122/79487290-50b79380-8018-11ea-8f43-9968c5f1f066.png)

**Comment by tim-hellhake** [comment]
I added the `TemperatureSensor` capability for temperature values and the `MultiLevelSensor` capability for P1 (PM10) values.

With the new update it should look like this:

![image](https://user-images.githubusercontent.com/17127122/79618768-47f3ba00-810b-11ea-8065-7527aa29b57e.png)

If you are more interested in the humidity values than in the temperature values I could add `MultiLevelSensor` capability for humidity values too.
In case a Sensor has humidity and P1 values I would have to choose one of them though.

**Comment by tim-hellhake** [comment]
Btw. there is already an issue in capabilities repo for a `HumiditySensor`:

https://github.com/mozilla-iot/schemas/issues/30

As soon that would be implemented, you could decide whether you would like to see the temperature property or the humidity property.
That would require changes in the gateway, though, as the UI needs a representation for every new capability.

**Comment by tim-hellhake** [comment]
Btw. there is already an issue in the capability repo for a HumiditySensor:

mozilla-iot/schemas#30

As soon that would be implemented, you could decide whether you would like to see the temperature property or the humidity property.
That would require changes in the gateway, though, as the UI needs a representation for every new capability.

**Comment by barts2108** [comment]
Seen it. Its nice now to see the real values.

**Comment by tim-hellhake** [comment]
Is there anything left or can I close the issue?

**Comment by barts2108** [comment]
Can be closed

**Comment by tim-hellhake** [comment]
Good :)
If you have any ideas for improvement feel free to open another issue.
